name: Release Extension

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release ZIP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP file
        run: zip -r instaYou.zip InstaYou

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: instaYou.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}